echo_bot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  diff_drive_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'wheel_left_joint'
    right_wheel : 'wheel_right_joint'

    publish_rate: 25.0
    cmd_vel_timeout: 1.0
    wheel_separation : 0.156
    wheel_radius : 0.029
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # tf
    #enable_odom_tf: true
    base_frame_id: base_link
    odom_frame_id: odom

    # limits
    # linear:
    #   x:
    #     has_velocity_limits    : true
    #     max_velocity           :  0.55 # m/s
    #     min_velocity           : -0.55 # m/s
    #     has_acceleration_limits: true
    #     max_acceleration       :  1.0 # m/s^2
    #     min_acceleration       : -1.0 # m/s^2
    # angular:
    #   z:
    #     has_velocity_limits    : true
    #     max_velocity           :  1.5 # rad/s
    #     min_velocity           : -1.5 # rad/s
    #     has_acceleration_limits: true
    #     max_acceleration       :  1.0  # rad/s^2
    #     min_acceleration       : -1.0 # rad/s^2

  leg_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - upper_leg_left_joint
      - upper_leg_right_joint
    gains:
      upper_leg_left_joint:   {p: 100, i: 0.01, d: 10}
      upper_leg_right_joint:  {p: 100, i: 0.01, d: 10}

  # right_leg_trajectory_controller:
  #   type: "position_controllers/JointTrajectoryController"
  #   joints:
  #     - upper_leg_right_joint

  # upper_left_leg_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: upper_leg_left_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # upper_right_leg_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: upper_leg_right_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  lower_left_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: lower_leg_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lower_right_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: lower_leg_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  upper_side_left_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: upper_side_leg_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  upper_side_right_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: upper_side_leg_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
